### ISSUE TITLE
当選確率が2倍になってしまう

### ISSUE THREAD

**Issue by sh-miyoshi** [kinoppyd/zoom-gacha#1]
## 問題

Zoomに一度入った後抜けて再度入ると2人になって表示されてしまいます
そのためガチャの当選確率が2倍になって公平感が損なわれています

## どうしてほしいか

再入室しても同じユーザーは一人としてほしい

**Comment by kinoppyd** [comment]
[List meeting participants - Dashboards - Zoom API - API Reference - Zoom Developer - Technical Documentation and Reference](https://marketplace.zoom.us/docs/api-reference/zoom-api/dashboards/dashboardmeetingparticipants)

> Information about the meeting participants. If a participant left a meeting and rejoined the same meeting, their information will appear as many times as they joined the meeting.

ウケる

**Comment by kinoppyd** [comment]
#2
